Implement LBC
elizar/toink-up pull request #4
Opened 2018-01-26 13:35 UTC by technowar

2018-01-30 06:36 UTC, penzur requested changes

2018-01-30 06:36 UTC, penzur commented on parcel/methods.go
> +func lbcPost(tn string) (statuses []*Status, err error) {
Ngano naa mani `Post` nga suffix @technowar? Pwede ra guro `lbc` 😃

2018-01-30 06:37 UTC, technowar commented on parcel/methods.go
> +func lbcPost(tn string) (statuses []*Status, err error) {
Nyahahaha abi nako suffix pod na sa phlPost ang `Post`. Karon ra ko naka realize nga dili diay. 😂  will change it later :D

2018-01-31 17:29 UTC, elizar commented on parcel/methods.go
> +func lbcPost(tn string) (statuses []*Status, err error) {
lols i change na diha ay sig' slack2x diha 😆

2018-03-01 06:59 UTC, technowar commented
@elizar ay sig slack dira, nahuman na nako update ang pr haha

2018-03-01 07:00 UTC, merged

2018-03-01 07:00 UTC, penzur commented
done @technowar

2018-03-01 07:00 UTC, technowar commented
Thanks :D